-- THIS IS HOW YOU COMMENT
-- THIS IS A SIMPLE SELECT STATEMENT TO SELECT ALL COLUMNS FROM EMPLOYEES TABLE
-- SQL STATEMENTS END WITH SEMICOLONS
-- SQL IS CASE-INSENSITIVE
-- * MEANS EVERYTHING -- ALL COLUMNS
SELECT * FROM EMPLOYEES;
-- you can write in lowercase as well

-- IF YOU SELECT COLUMN OR TABLE THAT DOES NOT EXIST IT WILL SHOW ERROR
SELECT * FROM BREAKFAST; -- THIS IS NOT A VALID TABLE NAME

-- SELECTING SPECIFIC COLUMN BY PROVIDING COLUMN NAMES AND SEPARATING BY COMMA

-- TASKS : EXPLORE TO FIND OUT ALL OTHER EXISTING TABLE
-- AND DISPLAY ALL THE CONTENT OF THOSE TABLES IN QUERY RESULT BY RUNNING THEM

