-- FIND AVERAGE SALARY OF EACH DEPARTMENT
-- REMOVE THE NULL DEPARTMENT_ID FROM THE RESULT
SELECT ROUND(AVG(SALARY)) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING AVG(SALARY) > 8000;
-- CONTINUE FROM ABOVE QUERY
-- ONLY DISPLAY THE RESULT IF AVERAGE SALARY IS MORE THAN 8000