-- FIND AVERAGE SALARY OF EACH DEPARTMENT
-- REMOVE THE NULL DEPARTMENT_ID FROM THE RESULT
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY))
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 8000;
-- CONTINUE FROM ABOVE QUERY
-- ONLY DISPLAY THE RESULT IF AVERAGE SALARY IS MORE THAN 8000

-- LOWER, UPPER, LENGTH
-- FIND ALL UPPERCASE FIRST NAMES, LENGTH OF FIRST_NAME, LAST_NAME AND LENGTH OF FULL_NAME
-- SORT THE RESULT BY 3RD COLUMN
SELECT UPPER(FIRST_NAME), LENGTH(FIRST_NAME), LENGTH(LAST_NAME), LENGTH(FIRST_NAME || LAST_NAME)
FROM EMPLOYEES
ORDER BY 3;